/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;

import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import Busyness.AdminBusyness;
import Busyness.BaseBusyness;
import Busyness.BookBusyness;
import Busyness.UploadBean;
import struts.form.addBooksForm;

public class AddBookAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		addBooksForm addBooksForm = (addBooksForm) form;// TODO Auto-generated method stub
		AdminBusyness ab=new AdminBusyness();
        UploadBean ub=new UploadBean();
		
		String path=request.getRealPath("/");
		
		FormFile file=addBooksForm.getFile();
		
		String fileName=file.getFileName();
		//上传后的文件名字
		String fileinname=BaseBusyness.getStringID()+fileName.substring(fileName.lastIndexOf("."));
		//上传后的路径 
		path=path+"files/"+fileinname;
		if(ub.upload(path, file)){
		if(ab.addBook(addBooksForm,fileinname)){
			return mapping.findForward("success");
		}else{
			return mapping.findForward("fail");
		}
		}
		return mapping.findForward("success");
	}
}