/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import Busyness.AdminBusyness;
import Entity.BookDetail;

import struts.form.UpdateForm;

public class AdminDetailBookAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String bookid=request.getParameter("bookid");
		AdminBusyness ab=new AdminBusyness();
		BookDetail bd=ab.getABookDetail(bookid);
		request.setAttribute("adetailbook",bd);
		String flag=request.getParameter("flag");
		if("updatebook".equals(flag)){
			return mapping.findForward("update");
		}else{
			return mapping.findForward("detail");
		}
		// TODO Auto-generated method stub
		
	}
	
}