/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import struts.form.LoginForm;

import Busyness.BookBusyness;
import Busyness.MemberBusyness;
import Entity.CartBooks;
import Entity.Member;

public class CartAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String flag = request.getParameter("flag");
		HttpSession session = request.getSession(true);

		String sessionid = session.getId();
		LoginForm userid = (LoginForm) session.getAttribute("user");
		BookBusyness bb = new BookBusyness();
		if ("delcart".equals(flag)) {
			ArrayList<CartBooks> al = bb.getCartAllBooks(sessionid);
			request.setAttribute("cartbooks", al);
			if (al.size() > 0) {
				request.setAttribute("tatol", al.get(al.size() - 1).getTotal());
			}
		} else {
			String bookid = request.getParameter("bookid");

			String mkrum = request.getParameter("mkrum");
			// 在购物车中
			if (bb.isexit(bookid, sessionid)) {
				bb.updatecart(bookid, sessionid, Integer.parseInt(mkrum));// 更新购物车
			} else {// 不在购物车中
				if (bb.isCartexit(sessionid)) {// 购物车存在
					bb.addcart(bookid, sessionid, Integer.parseInt(mkrum));// 添加到购物车
				} else {// 购物车不存在
					bb.createcart(sessionid, userid);// 创建购物车
					bb.addcart(bookid, sessionid, Integer.parseInt(mkrum));// 添加到购物车
				}
			}
			// 查询购物车
			ArrayList<CartBooks> al = bb.getCartAllBooks(sessionid);
			request.setAttribute("cartbooks", al);
			if (al.size() > 0) {
				request.setAttribute("tatol", al.get(al.size() - 1).getTotal());
			}
		}
		// TODO Auto-generated method stub
		return mapping.findForward("success");
	}
}
