/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import Busyness.MemberBusyness;
import struts.form.MemberAddForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-20-2013
 * 
 * XDoclet definition:
 * @struts.action path="/memberAdd" name="memberAddForm" scope="request"
 * @struts.action-forward name="Fail" path="/MemberAdd.jsp"
 * @struts.action-forward name="Success" path="/HomePage.jsp"
 */
public class MemberAddAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		MemberAddForm memberAddForm = (MemberAddForm) form;
		MemberBusyness mb=new MemberBusyness();
		request.setAttribute("memberinfo",memberAddForm);
		
		if(mb.memberInfo(memberAddForm)){
			return mapping.findForward("Success");
		}else{
			return mapping.findForward("Fail");
		}
	}
}