/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import Busyness.AdminBusyness;

import Entity.Member;

/** 
 * MyEclipse Struts
 * Creation date: 06-13-2013
 * 
 * XDoclet definition:
 * @struts.action
 */
public class QueryCustomAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdminBusyness ub=new AdminBusyness();
		ArrayList<Member> m=ub.getAllUser();
		request.setAttribute("customlist", m);
		String flag=request.getParameter("flag");
		if("del".equals(flag)){
			return mapping.findForward("delete");
		}else{
			return mapping.findForward("query");
		}
	}
}