/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import Busyness.AdminBusyness;
import Entity.BookDetail;

public class QueryBookAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String flag=request.getParameter("flag");
		AdminBusyness ab=new AdminBusyness();
		ArrayList<BookDetail> abd=ab.getDetailBooks();
		request.setAttribute("booklist", abd);
		if("updatebook".equals(flag)){
			return mapping.findForward("modify");
			
		}
		else if("delbook".equals(flag)){
			return mapping.findForward("delete");
			
		}else{
			return mapping.findForward("query");
			
		}
		
	}
}