/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import Busyness.BookBusyness;
import Entity.CartBooks;

public class SelectcartAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
HttpSession session=request.getSession(true);
		
		String sessionid=session.getId();
		BookBusyness bb=new BookBusyness();
		//≤È—Øπ∫ŒÔ≥µ
		ArrayList<CartBooks> al=bb.getCartAllBooks(sessionid);
		request.setAttribute("cartbooks", al);
		if(al.size()>0)
			request.setAttribute("tatol", al.get(al.size()-1).getTotal());
		// TODO Auto-generated method stub
		return mapping.findForward("success");
		
	}
}