/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;
import java.util.ArrayList;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.*;
import Busyness.BookBusyness;
import Entity.BookDetail;

public class showDetailBooksAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String categoryid = request.getParameter("categoryid");
		BookBusyness bb = new BookBusyness();
	
		ArrayList<BookDetail> bd = bb.showDetailBooks(categoryid);
		request.setAttribute("booklist", bd);
		return mapping.findForward("success");
		
		

	}
}