/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import Busyness.BaseBusyness;
import Busyness.BookBusyness;
import Entity.CartBooks;

import struts.form.LoginForm;

public class SubmitorderAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
        HttpSession session=request.getSession(true);
		BookBusyness bb=new BookBusyness();
		String sessionid=session.getId();
		LoginForm userid = (LoginForm) session.getAttribute("user");
		String amount=request.getParameter("amount");
		String orderid=BaseBusyness.getStringID();
        bb.addOrder(sessionid,amount,orderid,userid);//生成订单
		bb.addOrderDetail(sessionid, orderid);//生成订单详情
		//更新商品库存
		ArrayList<CartBooks> al=bb.getCartAllBooks(sessionid);//查询购物车
		for(int i=0;i<al.size();i++){
			bb.updateBooksNum(Integer.parseInt(al.get(i).getShoppingnum()), al.get(i).getBookid());
		}
		bb.updateCartStatus(sessionid);//删除购物车
		bb.updateCartDetailStatus(sessionid);
		request.setAttribute("orderid", orderid);
		
		return mapping.findForward("success");
	}
}