/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-20-2013
 * 
 * XDoclet definition:
 * @struts.form name="memberAddForm"
 */
public class MemberAddForm extends ActionForm {
	/*
	 * Generated fields
	 */
	private String ID;
	public String getID() {
		return ID;
	}

	public void setID(String iD) {
		ID = iD;
	}

	/** ADDR2 property */
	private String ADDR2;

	/** ZIP_CD property */
	private String ZIP_CD;

	/** ADDR1 property */
	private String ADDR1;

	/** sex property */
	private String sex;

	/** ADDR3 property */
	private String ADDR3;

	/** NM1 property */
	private String NM1;

	/** NM2 property */
	private String NM2;

	/** TEL1 property */
	private String TEL1;

	/** JOB property */
	private String JOB;

	/** TEL2 property */
	private String TEL2;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the ADDR2.
	 * @return String
	 */
	public String getADDR2() {
		return ADDR2;
	}

	/** 
	 * Set the ADDR2.
	 * @param ADDR2 The ADDR2 to set
	 */
	public void setADDR2(String ADDR2) {
		this.ADDR2 = ADDR2;
	}

	/** 
	 * Returns the ZIP_CD.
	 * @return String
	 */
	public String getZIP_CD() {
		return ZIP_CD;
	}

	/** 
	 * Set the ZIP_CD.
	 * @param ZIP_CD The ZIP_CD to set
	 */
	public void setZIP_CD(String ZIP_CD) {
		this.ZIP_CD = ZIP_CD;
	}

	/** 
	 * Returns the ADDR1.
	 * @return String
	 */
	public String getADDR1() {
		return ADDR1;
	}

	/** 
	 * Set the ADDR1.
	 * @param ADDR1 The ADDR1 to set
	 */
	public void setADDR1(String ADDR1) {
		this.ADDR1 = ADDR1;
	}

	/** 
	 * Returns the sex.
	 * @return String
	 */
	public String getSex() {
		return sex;
	}

	/** 
	 * Set the sex.
	 * @param sex The sex to set
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/** 
	 * Returns the ADDR3.
	 * @return String
	 */
	public String getADDR3() {
		return ADDR3;
	}

	/** 
	 * Set the ADDR3.
	 * @param ADDR3 The ADDR3 to set
	 */
	public void setADDR3(String ADDR3) {
		this.ADDR3 = ADDR3;
	}

	/** 
	 * Returns the NM1.
	 * @return String
	 */
	public String getNM1() {
		return NM1;
	}

	/** 
	 * Set the NM1.
	 * @param NM1 The NM1 to set
	 */
	public void setNM1(String NM1) {
		this.NM1 = NM1;
	}

	/** 
	 * Returns the NM2.
	 * @return String
	 */
	public String getNM2() {
		return NM2;
	}

	/** 
	 * Set the NM2.
	 * @param NM2 The NM2 to set
	 */
	public void setNM2(String NM2) {
		this.NM2 = NM2;
	}

	/** 
	 * Returns the TEL1.
	 * @return String
	 */
	public String getTEL1() {
		return TEL1;
	}

	/** 
	 * Set the TEL1.
	 * @param TEL1 The TEL1 to set
	 */
	public void setTEL1(String TEL1) {
		this.TEL1 = TEL1;
	}

	/** 
	 * Returns the JOB.
	 * @return String
	 */
	public String getJOB() {
		return JOB;
	}

	/** 
	 * Set the JOB.
	 * @param JOB The JOB to set
	 */
	public void setJOB(String JOB) {
		this.JOB = JOB;
	}

	/** 
	 * Returns the TEL2.
	 * @return String
	 */
	public String getTEL2() {
		return TEL2;
	}

	/** 
	 * Set the TEL2.
	 * @param TEL2 The TEL2 to set
	 */
	public void setTEL2(String TEL2) {
		this.TEL2 = TEL2;
	}
}