/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-12-2013
 * 
 * XDoclet definition:
 * @struts.form name="registForm"
 */
public class RegistForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** PW property */
	private String PW;

	/** PW_CFM property */
	private String PW_CFM;

	/** ID property */
	private String ID;

	/** ID_CFM property */
	private String ID_CFM;
	
	private String flag;
	/*
	 * Generated Methods
	 */

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the PW.
	 * @return String
	 */
	public String getPW() {
		return PW;
	}

	/** 
	 * Set the PW.
	 * @param PW The PW to set
	 */
	public void setPW(String PW) {
		this.PW = PW;
	}

	/** 
	 * Returns the PW_CFM.
	 * @return String
	 */
	public String getPW_CFM() {
		return PW_CFM;
	}

	/** 
	 * Set the PW_CFM.
	 * @param PW_CFM The PW_CFM to set
	 */
	public void setPW_CFM(String PW_CFM) {
		this.PW_CFM = PW_CFM;
	}

	/** 
	 * Returns the ID.
	 * @return String
	 */
	public String getID() {
		return ID;
	}

	/** 
	 * Set the ID.
	 * @param ID The ID to set
	 */
	public void setID(String ID) {
		this.ID = ID;
	}

	/** 
	 * Returns the ID_CFM.
	 * @return String
	 */
	public String getID_CFM() {
		return ID_CFM;
	}

	/** 
	 * Set the ID_CFM.
	 * @param ID_CFM The ID_CFM to set
	 */
	public void setID_CFM(String ID_CFM) {
		this.ID_CFM = ID_CFM;
	}
}